"""Gzip member vectors (blobs generated by CPython gzip)."""

from std.sys import exit
from std.testing import TestSuite, assert_equal, assert_true

from memveil.platform.gzip import gunzip_member
from memveil.platform.hash import sha256_hex

comptime _ZLIB = "libz.so.1"


def _basic() -> List[UInt8]:
    return List[UInt8]([
        UInt8(31), UInt8(139), UInt8(8), UInt8(0), UInt8(0), UInt8(0),
        UInt8(0), UInt8(0), UInt8(2), UInt8(255), UInt8(115),
        UInt8(246), UInt8(247), UInt8(115), UInt8(243), UInt8(116),
        UInt8(143), UInt8(15), UInt8(14), UInt8(119), UInt8(12),
        UInt8(176), UInt8(205), UInt8(227), UInt8(114), UInt8(134),
        UInt8(240), UInt8(60), UInt8(189), UInt8(161), UInt8(140),
        UInt8(128), UInt8(32), UInt8(127), UInt8(103), UInt8(219),
        UInt8(74), UInt8(46), UInt8(101), UInt8(133), UInt8(146),
        UInt8(212), UInt8(226), UInt8(18), UInt8(133), UInt8(228),
        UInt8(252), UInt8(188), UInt8(180), UInt8(204), UInt8(116),
        UInt8(46), UInt8(0), UInt8(45), UInt8(1), UInt8(240),
        UInt8(222), UInt8(51), UInt8(0), UInt8(0), UInt8(0),
]    )


def test_basic_roundtrip() raises:
    var blob = _basic()
    var out = gunzip_member(Span(blob), String(_ZLIB))
    assert_true(out.ok)
    assert_equal(len(out.data), 51)
    assert_equal(
        sha256_hex(Span(out.data)),
        String(
            "c7fae0d6bf4358c883803ebea802a2e6"
            "b5b7eea48b795daa9ce4e24d4b294748"
        ),
    )


def test_empty_member() raises:
    var blob = List[UInt8]([
        UInt8(31), UInt8(139), UInt8(8), UInt8(0), UInt8(0), UInt8(0),
        UInt8(0), UInt8(0), UInt8(2), UInt8(255), UInt8(3), UInt8(0),
        UInt8(0), UInt8(0), UInt8(0), UInt8(0), UInt8(0), UInt8(0),
        UInt8(0), UInt8(0),
]    )
    var out = gunzip_member(Span(blob), String(_ZLIB))
    assert_true(out.ok)
    assert_equal(len(out.data), 0)


def test_fname_member() raises:
    var blob = List[UInt8]([
        UInt8(31), UInt8(139), UInt8(8), UInt8(8), UInt8(116),
        UInt8(250), UInt8(196), UInt8(106), UInt8(2), UInt8(255),
        UInt8(99), UInt8(111), UInt8(110), UInt8(102), UInt8(105),
        UInt8(103), UInt8(0), UInt8(115), UInt8(246), UInt8(247),
        UInt8(115), UInt8(243), UInt8(116), UInt8(143), UInt8(15),
        UInt8(14), UInt8(119), UInt8(12), UInt8(176), UInt8(205),
        UInt8(227), UInt8(114), UInt8(134), UInt8(240), UInt8(60),
        UInt8(189), UInt8(161), UInt8(140), UInt8(128), UInt8(32),
        UInt8(127), UInt8(103), UInt8(219), UInt8(74), UInt8(46),
        UInt8(101), UInt8(133), UInt8(146), UInt8(212), UInt8(226),
        UInt8(18), UInt8(133), UInt8(228), UInt8(252), UInt8(188),
        UInt8(180), UInt8(204), UInt8(116), UInt8(46), UInt8(0),
        UInt8(45), UInt8(1), UInt8(240), UInt8(222), UInt8(51),
        UInt8(0), UInt8(0), UInt8(0),
]    )
    var out = gunzip_member(Span(blob), String(_ZLIB))
    assert_true(out.ok)
    assert_equal(len(out.data), 51)
    assert_equal(
        sha256_hex(Span(out.data)),
        String(
            "c7fae0d6bf4358c883803ebea802a2e6"
            "b5b7eea48b795daa9ce4e24d4b294748"
        ),
    )


def test_bad_magic() raises:
    var blob = List[UInt8]([
        UInt8(0), UInt8(0), UInt8(8), UInt8(0), UInt8(0), UInt8(0),
        UInt8(0), UInt8(0), UInt8(0), UInt8(0), UInt8(3), UInt8(0),
        UInt8(0), UInt8(0), UInt8(0), UInt8(0), UInt8(0), UInt8(0),
]    )
    var out = gunzip_member(Span(blob), String(_ZLIB))
    assert_true(not out.ok)


def test_truncated() raises:
    var blob = _basic()
    var cut = List[UInt8]()
    for i in range(len(blob) - 8):
        cut.append(blob[i])
    var out = gunzip_member(Span(cut), String(_ZLIB))
    assert_true(not out.ok)


def test_corrupt() raises:
    var blob = _basic()
    blob[12] = UInt8(Int(blob[12]) ^ 0xFF)
    var out = gunzip_member(Span(blob), String(_ZLIB))
    assert_true(not out.ok)


def test_huge_isize_refused() raises:
    var blob = _basic()
    blob[len(blob) - 4] = UInt8(0)
    blob[len(blob) - 3] = UInt8(0)
    blob[len(blob) - 2] = UInt8(16)
    blob[len(blob) - 1] = UInt8(1)
    var out = gunzip_member(Span(blob), String(_ZLIB))
    assert_true(not out.ok)
    assert_equal(out.message, String("gzip output too big"))


def test_missing_library_uncheckable() raises:
    var blob = _basic()
    var out = gunzip_member(
        Span(blob), String("libmemveil-no-such-soname.so.6")
    )
    assert_true(not out.ok)
    assert_equal(out.message, String("zlib unavailable"))


def run() raises -> Int:
    var suite = TestSuite()
    suite.test[test_basic_roundtrip]()
    suite.test[test_empty_member]()
    suite.test[test_fname_member]()
    suite.test[test_bad_magic]()
    suite.test[test_truncated]()
    suite.test[test_corrupt]()
    suite.test[test_huge_isize_refused]()
    suite.test[test_missing_library_uncheckable]()
    suite^.run()
    return 0


def main() raises:
    var code = run()
    if code != 0:
        exit(code)
